### ISSUE TITLE
Add Github action pipeline for running compile and tests when PR is made

### ISSUE THREAD

**Issue by OlivierAlbertini** [VilledeMontreal/node-general-utils#7]
We should add a Github action for testing the library when PR is made.
```
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run lint
      - run: npm test
        env:
          CI: true
```
